### ISSUE TITLE
[FIREBASE] Scroll bottom when scroll to top to load more message

### ISSUE THREAD

**Issue by luuthi** [luuthi/chatapp-angular-firebase#13]
bị nhẩy scroll xuống bottom khi cuộn lên trên để get thêm message

**Comment by ducdk** [comment]
cố fix xong r ngủ nha a

**Comment by ducdk** [comment]
tạo biến lưu position when scroll 
sau khi loading xong thì set lại position theo active scroll 
:

**Comment by luuthi** [comment]
Done!
