### ISSUE TITLE
[PROJECT] Run app

### ISSUE THREAD

**Issue by ducdk** [luuthi/chatapp-angular-firebase#3]
Hiện giờ run được app

**Comment by luuthi** [comment]
1. run npm install bị lỗi package node-sass => cài bằng yarn
2. khi chạy ng serve bị lỗi :
`ERROR in src/app/views/dashboard/smart/dashboard-timetable/dashboard-timetable.component.ts(263,16): error TS2459: Type '{ height: any; hourPerStep: any; newBlock: any; event: any; }' has no property 'moveBlock' and no string index signature.`

**Comment by ducdk** [comment]
update thanh coong
