### ISSUE TITLE
[FIREBASE] Add Authentication 

### ISSUE THREAD

**Issue by luuthi** [luuthi/chatapp-angular-firebase#4]
- [x] auth by google

**Comment by luuthi** [comment]
done authen by google

**Comment by ducdk** [comment]
A sửa lại Conversion Code là của typescript nên a đặt biết vd như curUser k nên dùng cur_user như của python :3

**Comment by ducdk** [comment]
Nếu e mà khi trình duyệt lưu cache thì e k get được thông tin người login vào nên k thể check được thằng nào đang đăng nhập
