### ISSUE TITLE
Create data demo, model

### ISSUE THREAD

**Issue by ducdk** [luuthi/chatapp-angular-firebase#6]
- [x] create data demo (1)
- [x] model follow data demo (1)

**Comment by luuthi** [comment]
create model done

**Comment by luuthi** [comment]
create data demo done

**Comment by ducdk** [comment]
phần login xong tạo conversation cho user đó với 1 admin thì a tạo thêm 1 conversation ra nhưng chưa add message cho nó

**Comment by luuthi** [comment]
ý chú là chưa có field message á.
